# Generated by Django 5.0.14 on 2026-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('request_desc', models.TextField(max_length=4000)),
                ('comment', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('cancel', 'Cancel'), ('completed', 'Completed'), ('pending', 'Pending')], default='new', max_length=20)),
            ],
        ),
    ]
